POST http://localhost:5000/signup
Content-Type: application/json

{"name": "Jack", "email": "test@test.com", "password": "password"}

###
POST http://localhost:5000/login
Content-Type: application/json

{"email": "test@test.com", "password": "password"}

###

GET http://localhost:5000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJwYXNzd29yZCI6InBhc3N3b3JkIiwiaWF0IjoxNjU2Mjc0NzYyLCJleHAiOjE2NTYyNzgzNjJ9.eb-rwD1tdgGl9tRoG2veDrs4MFmJYAFCgJqW3R1a4X0

###